filedo:
  uploadPath: localhost:9091
  upload: C:/web/hzcy/uploaded_files/
logging:
  level:
    root: info
    com.palmble: debug
    com.palmble.**.dao: debug
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gyds?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root

    initialSize: 10
    minIdle: 10
    maxActive: 30
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: M2d59ef9fe$
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接notifyUrl
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    database: 6

wx:
  appid: wx7041f7df1c9e66c2
  secret: afb64d47c9062ab4c47fb34546b22cb5
  backUrl: http://hezhong.65g.cn/auth/callback
#  appid: wx4334431741b35429
#  secret: 2c2f47e624eed7043be7cc55f1fbb428
#  backUrl: http://pzmkfs.natappfree.cc/auth/callback
const:
  APPID : wx7041f7df1c9e66c2
  MCHID: 1441549702
  KEY: nT77Y44C7M5Y7v74zo7fT66h65MugBZz
  APPSECRET: afb64d47c9062ab4c47fb34546b22cb5
  notifyUrl: http://hezhong.65g.cn/pay/notify
  keyPath: C:/web/hzcy/apiclient/apiclient_cert.p12