filedo:
  uploadPath: /var/uploaded_files/
logging:
  level:
    root: info
    com.fly: debug
    com.fly.**.dao: debug
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.114.82.200:3306/gyds?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    #url: jdbc:mysql://192.168.124.101:3306/gyds?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: qweasdzxc123
    initialSize: 10
    minIdle: 10
    maxActive: 30
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
      host: localhost
      port: 6379
      password: M2d59ef9fe$
      # 连接超时时间（毫秒）
      timeout: 10000
      jedis:
        pool:
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池中的最小空闲连接
          min-idle: 10
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 100
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
      database: 6

  
wechat:
  open:
    componentAppId: wx8f042090d19f8ee0
    componentSecret: 5d77193a6f39799d6892d94bcd7e3471
    componentToken: wangyanke
    componentAesKey: 
wx:
  appid: wx56c5f184879412f4
  secret: f579870d16cc2fc222ff2b20963be73a
  backUrl: http://mlbdenet.nat300.top/auth/callback
  
  
  
wxpay:
  appid: wx561ae40290380b04
  secret: 2b01a7d96a1e34d3cecf80be87852d53
  mch_id: 1309497501
  key: fenlegou20160226fenlegou20160226  
